"""
workflow - Migrated from LangGraph to openJiuwen

Auto-generated by lg2jiuwentool
Source framework: langgraph
"""


import os
from typing import Dict, Any, Optional, List
os.environ['LLM_SSL_VERIFY'] = 'false'
# openJiuwen imports
from openjiuwen.core.workflow.base import Workflow
from openjiuwen.core.component.start_comp import Start
from openjiuwen.core.component.end_comp import End
from openjiuwen.core.component.base import WorkflowComponent
from openjiuwen.core.runtime.base import ComponentExecutable, Input, Output
from openjiuwen.core.runtime.runtime import Runtime
from openjiuwen.core.runtime.workflow import WorkflowRuntime
from openjiuwen.core.context_engine.base import Context

# LLM imports
from openjiuwen.core.utils.llm.model_library.openai import OpenAIChatModel

# Tool imports
from openjiuwen.core.utils.tool.param import Param
from openjiuwen.core.utils.tool.tool import tool

# Additional imports
from pydantic import BaseModel, Field
import json
import httpx

# ============ Global Variables ============

SENIVERSE_API_KEY = 'xxxxxxxxx'

# ============ Tool Definitions ============

@tool(
    name="get_weather",
    description="按城市+自然语言日期查天气（使用心知天气API）",
    params=[
        Param(name="city", description="city", type="string", required=True),
        Param(name="date", description="date", type="string", required=True)
    ]
)
def get_weather(city: str, date: str) -> str:
    """
    按城市+自然语言日期查天气（使用心知天气API）
    """
    day_index = {'今天': 0, '明天': 1, '后天': 2}.get(date, 0)
    url = f'https://api.seniverse.com/v3/weather/daily.json?key={SENIVERSE_API_KEY}&location={city}&language=zh-Hans&unit=c&start={day_index}&days=1'
    try:
        resp = httpx.get(url, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        result = data['results'][0]
        location = result['location']['name']
        daily = result['daily'][0]
        return f"{location} {daily['date']}: {daily['low']}~{daily['high']}°C, 白天{daily['text_day']}, 夜间{daily['text_night']}"
    except httpx.HTTPStatusError as e:
        return f'天气服务异常：HTTP {e.response.status_code}'
    except (KeyError, IndexError) as e:
        return f'天气数据解析异常：{e}'
    except Exception as e:
        return f'天气服务异常：{e}'


# ============ Component Definitions ============

# LLM Configuration
# TODO: Configure your LLM provider settings
MODEL_PROVIDER = "openai"
MODEL_NAME = "glm-4-flash"
API_BASE = os.getenv("OPENAI_API_BASE", "https://open.bigmodel.cn/api/paas/v4/")
API_KEY = os.getenv("OPENAI_API_KEY", "xxxxxxxxxxxxxxxxxxxxxxxxx")

class ExtractComponent(WorkflowComponent, ComponentExecutable):
    """LLM 提取 city & date，缺一个就报错"""

    def __init__(self):
        super().__init__()
        self._llm = OpenAIChatModel(
            api_key=API_KEY,
            api_base=API_BASE,
            timeout=30,
        )

    async def invoke(self, inputs: Input, runtime: Runtime, context: Context) -> Output:
        # Initialize output variables
        city = None
        date = None
        error = None

        sys_prompt = '用户会输入一句话，请提取“城市”和“日期”。\n日期可以是：今天、明天、后天 等。\n如果城市或日期缺失，请只返回 ERROR: 缺失城市 或 ERROR: 缺失日期，不要多余文字。\n否则返回 JSON: {"city": "城市", "date": "日期"}'
        messages = [{'role': 'system', 'content': sys_prompt}, {'role': 'user', 'content': inputs.get("sentence")}]
        llm_response = await self._llm.ainvoke(model_name=MODEL_NAME, messages=messages, temperature=0.7, top_p=0.9)
        ans = llm_response.content.strip()
        print('llm ans:', ans)
        try:
            import json
            obj = json.loads(ans)
            city = obj['city']
            date = obj['date']
        except Exception:
            error = ans

        return {"city": city, "date": date, "error": error}


class CallWeatherComponent(WorkflowComponent, ComponentExecutable):
    """直接调用天气工具获取结果"""

    def __init__(self):
        super().__init__()

    async def invoke(self, inputs: Input, runtime: Runtime, context: Context) -> Output:
        # Initialize output variables
        weather = None
        error = None

        city = inputs.get('city')
        date = inputs.get('date')
        if not city or not date:
            error = '缺少城市或日期参数'
            return {"error": error}
        result = get_weather.invoke({'city': city, 'date': date})
        print('weather result:', result)
        weather = result

        return {"weather": weather, "error": error}


# ============ Router Functions ============

def extract_router(runtime: Runtime) -> str:
    """
    Router function for extract conditional connection.
    
    Original LangGraph function: route_after_extract
    """
    return 'end' if runtime.get_global_state('extract.error') else 'call_weather'

# ============ Workflow Builder ============

def create_workflow() -> Workflow:
    """Create the openJiuwen workflow"""
    flow = Workflow()

    # Start component
    flow.set_start_comp(
        "start",
        Start(),
        inputs_schema={"sentence": "${user_inputs.sentence}", "city": "${user_inputs.city}", "date": "${user_inputs.date}", "error": "${user_inputs.error}"}
    )

    # extract component (conditional)
    flow.add_workflow_comp(
        "extract",
        ExtractComponent(),
        inputs_schema={"sentence": "${start.sentence}"}
    )

    # call_weather component
    flow.add_workflow_comp(
        "call_weather",
        CallWeatherComponent(),
        inputs_schema={"weather": "${start.weather}", "city": "${extract.city}", "date": "${extract.date}", "error": "${extract.error}"}
    )

    # End component
    flow.set_end_comp(
        "end",
        End(),
        inputs_schema={"call_weather_weather": "${call_weather.weather}", "call_weather_error": "${call_weather.error}", "extract_city": "${extract.city}", "extract_date": "${extract.date}", "extract_error": "${extract.error}"}
    )

    # Connections
    flow.add_connection("start", "extract")
    flow.add_connection("call_weather", "end")

    # Conditional connections (v2: using router functions)
    flow.add_conditional_connection("extract", router=extract_router)

    return flow

# ============ Main Entry Point ============

async def run_workflow(inputs: Dict[str, Any]) -> Dict[str, Any]:
    """Run the workflow with given inputs"""
    flow = create_workflow()
    runtime = WorkflowRuntime(
        workflow_id="workflow",
        session_id="default"
    )

    result = await flow.invoke(
        {"user_inputs": inputs},
        runtime
    )
    return result


# Example usage
if __name__ == "__main__":
    import asyncio

    # Example initial state
    initial_inputs = {
        "sentence": "明天北京天气",
        "city": "",
        "date": "",
        "weather": "",
        "error": ""
    }

    # Run the workflow
    result = asyncio.run(run_workflow(initial_inputs))
    print("Result:", result)
